<Project>
  <ItemGroup>
    <PackageVersion Include="NetVips" Version="3.2.0" />
    <PackageVersion Include="NetVips.Native.osx-arm64" Version="8.18.6" />
    <PackageVersion Include="NetVips.Native.linux-x64" Version="8.18.6" />
    <PackageVersion Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
