<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>plinth</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plinth.Pipeline\Plinth.Pipeline.csproj" />
    <ProjectReference Include="..\Plinth.Api\Plinth.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="NetVips.Native.osx-arm64" />
    <PackageReference Include="NetVips.Native.linux-x64" />
  </ItemGroup>

</Project>
