<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Plinth.Pipeline\Plinth.Pipeline.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetVips.Native.osx-arm64" />
    <PackageReference Include="NetVips.Native.linux-x64" />
    <PackageReference Include="NetVips.Native.linux-arm64" />
  </ItemGroup>

</Project>
