<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NetVips.Native.osx-arm64" />
    <PackageReference Include="NetVips.Native.linux-x64" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Plinth.Core\Plinth.Core.csproj" />
    <ProjectReference Include="..\..\src\Plinth.Pipeline\Plinth.Pipeline.csproj" />
    <ProjectReference Include="..\..\src\Plinth.Api\Plinth.Api.csproj" />
    <ProjectReference Include="..\..\src\Plinth.Cli\Plinth.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../fixtures/**" CopyToOutputDirectory="PreserveNewest" LinkBase="fixtures" />
  </ItemGroup>

</Project>