<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Plinth.Pipeline</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Plinth.Core/Plinth.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>
</Project>
